export const GET_COUNTERS = 'GET_COUNTERS';
export const GET_MANUFACTURERS = 'GET_MANUFACTURERS';
export const PUT_MANUFACTURER = 'PUT_MANUFACTURER';
export const DELETE_MANUFACTURER = 'DELETE_MANUFACTURER';
export const UPDATE_MANUFACTURER = 'UPDATE_MANUFACTURER';

export const GET_ERRORS = 'GET_ERRORS';
export const CREATE_MESSAGE = 'CREATE_MESSAGE';
export const INSPECTION_ALERT = 'INSPECTION_ALERT';

export const GET_CURRENT_STORE_PRODUCTS = 'GET_CURRENT_STORE_PRODUCTS';
export const PUT_PRODUCT = 'PUT_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const GET_QUANTITIES_FROM_OTHER_STORES = 'GET_QUANTITIES_FROM_OTHER_STORES ';

export const ADD_PRODUCT_FLOW = 'ADD_PRODUCT_FLOW';
export const GET_PRODUCT_FLOWS = 'GET_PRODUCT_FLOWS';
export const DELETE_PRODUCT_FLOW = 'DELETE_PRODUCT_FLOW';
export const GET_PF_BY_INVOICE_NUMBER = 'GET_PF_BY_INVOICE_NUMBER';

export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const GET_WAREHOUSES = 'GET_WAREHOUSES';

export const ADD_STORE = 'ADD_STORE';
export const GET_STORES = 'GET_STORES';
export const GET_CURRENT_STORE = 'GET_CURRENT_STORE';

export const ADD_CART_ITEM = 'ADD_CART_ITEM';
export const GET_CURRENT_CART_ITEMS = 'GET_CURRENT_CART_ITEMS';
export const GET_CART_ITEMS_FOR_CUSTOMER = 'GET_CART_ITEMS_FOR_CUSTOMER';
export const GET_CART_ITEMS_FOR_DAY= 'GET_CART_ITEMS_FOR_DAY';
export const UPDATE_CART_ITEM = 'UPDATE_CART_ITEM';
export const DELETE_CART_ITEM = 'DELETE_CART_ITEM';
export const GET_CURRENT_CART = 'GET_CURRENT_CART';
export const GET_CARTS_FOR_CUSTOMER = 'GET_CARTS_FOR_CUSTOMER';
export const GET_CARTS_FOR_DAY = 'GET_CARTS_FOR_DAY';
export const UPDATE_CART = 'UPDATE_CART';
export const DELETE_CART = 'DELETE_CART';

export const ADD_CUSTOMER = 'ADD_CUSTOMER';
export const GET_CUSTOMERS = 'GET_CUSTOMERS';

export const GET_INSTALMENTS = 'GET_INSTALMENTS';
export const ADD_INSTALMENT = 'ADD_INSTALMENT';

export const GET_INVOICES = 'GET_INVOICES';
export const ADD_INVOICE = 'ADD_INVOICE';
export const UPDATE_INVOICE = 'UPDATE_INVOICE';
export const DELETE_INVOICE = 'DELETE_INVOICE';

export const GET_TOP_SELLING_PRODUCTS_FOR_MONTH_BY_STORE = 'GET_TOP_SELLING_PRODUCTS_FOR_MONTH_BY_STORE';
export const GET_SALES_FREQUENCY_BY_MONTH = 'GET_SALES_FREQUENCY_BY_MONTH';
export const GET_PRODUCT_ADDITION_BY_MONTH = 'GET_PRODUCT_ADDITION_BY_MONTH';
export const GET_ANNUAL_APPROXIMATE_INCOME = 'GET_ANNUAL_APPROXIMATE_INCOME';
export const GET_WEEKLY_INCOME = 'GET_WEEKLY_INCOME';