# Generated by Django 2.1.7 on 2019-03-04 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bought_quantity', models.IntegerField(default=1)),
                ('combined_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('paid_on', models.DateTimeField()),
                ('amount_paid', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('raw_price', models.IntegerField()),
                ('raw_price_vat', models.FloatField(default=0)),
                ('regular_price', models.IntegerField()),
                ('available_quantity', models.IntegerField(default=0)),
                ('discount', models.IntegerField(blank=True, default=0, null=True)),
                ('discounted_price', models.IntegerField(blank=True, null=True)),
                ('stock_source', models.CharField(choices=[('WH', 'МАГАЦИН'), ('OEM', 'ДОБАВУВАЧ')], default='WH', max_length=100)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_io.Manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='ProductFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('operation', models.CharField(choices=[('ADD', 'ADDITION'), ('SUB', 'SUBTRACTION')], default='ADD', max_length=20)),
                ('manufacturer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store_io.Manufacturer')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store_io.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sold', models.DateTimeField(auto_now=True)),
                ('is_paid', models.BooleanField()),
                ('discount', models.FloatField(blank=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store_io.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('DRACEVO', 'DRACEVO'), ('ILINDEN', 'ILINDEN'), ('MADZARI', 'MADZARI')], default='DRACEVO', max_length=100)),
                ('products', models.ManyToManyField(to='store_io.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Tmp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='ДОМА', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='productflow',
            name='store',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store_io.Store'),
        ),
        migrations.AddField(
            model_name='productflow',
            name='warehouse',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store_io.Warehouse'),
        ),
        migrations.AddField(
            model_name='product',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store_io.Warehouse'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store_io.Product'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='sale',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store_io.Sale'),
        ),
    ]
