# Generated by Django 2.2 on 2019-04-09 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_io', '0003_auto_20190408_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='sale',
            field=models.OneToOneField(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='store_io.Sale'),
        ),
        migrations.AddField(
            model_name='productflow',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sale',
            name='registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sale',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
