# Generated by Django 2.2 on 2019-04-10 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_io', '0004_auto_20190409_1637'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
