# Generated by Django 2.2 on 2019-04-18 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store_io', '0006_auto_20190415_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='store',
            name='products',
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ManyToManyField(to='store_io.Store'),
        ),
        migrations.AddField(
            model_name='sale',
            name='employee',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sale',
            name='products',
            field=models.ManyToManyField(to='store_io.CartItem'),
        ),
        migrations.AlterField(
            model_name='store',
            name='location',
            field=models.CharField(choices=[('DR', 'DRACEVO'), ('IL', 'ILINDEN'), ('MA', 'MADZARI')], default='DR', max_length=100),
        ),
    ]
