# Generated by Django 2.2 on 2019-04-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_io', '0007_auto_20190418_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='location',
            field=models.CharField(max_length=20),
        ),
    ]
