# Generated by Django 2.2 on 2019-05-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_io', '0012_auto_20190507_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeproductquantity',
            name='product',
        ),
        migrations.AddField(
            model_name='storeproductquantity',
            name='product',
            field=models.ManyToManyField(to='store_io.Product'),
        ),
    ]
