# Generated by Django 2.2 on 2019-05-10 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_io', '0013_auto_20190508_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeproductquantity',
            name='product',
        ),
        migrations.AddField(
            model_name='storeproductquantity',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='store_io.Product'),
            preserve_default=False,
        ),
    ]
