# Generated by Django 2.2 on 2019-05-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_io', '0017_auto_20190510_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='total_sum',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
