# Generated by Django 2.2 on 2019-05-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_io', '0018_auto_20190510_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_sum',
            field=models.IntegerField(default=0),
        ),
    ]
