# Generated by Django 2.2 on 2019-05-14 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_io', '0019_auto_20190510_1958'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('product', 'sale')},
        ),
    ]
