# Generated by Django 2.2 on 2019-05-15 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_io', '0021_auto_20190514_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productflow',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='productflow',
            name='source',
            field=models.CharField(choices=[('WH', 'Магацин'), ('OEM', 'Добавувач'), ('CUS', 'Муштерија')], default='OEM', max_length=20),
        ),
        migrations.AddField(
            model_name='store',
            name='is_warehouse',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productflow',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store_io.Manufacturer'),
        ),
    ]
