# Generated by Django 2.2 on 2019-05-15 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_io', '0022_auto_20190515_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productflow',
            name='store',
        ),
        migrations.AddField(
            model_name='productflow',
            name='store_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_from', to='store_io.StoreProductQuantity'),
        ),
        migrations.AddField(
            model_name='productflow',
            name='store_to',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='store_to', to='store_io.StoreProductQuantity'),
            preserve_default=False,
        ),
    ]
