# Generated by Django 2.2 on 2019-05-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_io', '0024_auto_20190516_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='paid_sum',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='instalment',
            name='paid_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
