# Generated by Django 2.2 on 2019-05-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_io', '0025_auto_20190517_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date_sold',
            field=models.DateTimeField(),
        ),
    ]
