# Generated by Django 2.2 on 2019-05-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_io', '0026_auto_20190517_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date_sold',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
