# Generated by Django 2.2 on 2019-05-19 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_io', '0027_auto_20190517_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productflow',
            name='store_from',
        ),
        migrations.RemoveField(
            model_name='productflow',
            name='store_to',
        ),
        migrations.AddField(
            model_name='productflow',
            name='store_product_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sp_to', to='store_io.StoreProductQuantity'),
        ),
        migrations.AddField(
            model_name='productflow',
            name='store_product_to',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='sp_from', to='store_io.StoreProductQuantity'),
            preserve_default=False,
        ),
    ]
