# Generated by Django 2.2 on 2019-06-01 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_io', '0030_auto_20190530_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=20)),
                ('manufacturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store_io.Manufacturer')),
                ('product_flows', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store_io.ProductFlow')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer_code',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Email',
        ),
    ]
