# Generated by Django 2.2 on 2019-06-01 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_io', '0031_auto_20190601_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='product_flows',
        ),
        migrations.AddField(
            model_name='productflow',
            name='invoice',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store_io.Invoice'),
        ),
    ]
